# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_probs <- function(M, y, priors) {
    .Call('_BayesANT_compute_probs', PACKAGE = 'BayesANT', M, y, priors)
}

log_MultKmers_cpp <- function(x, x_tilde) {
    .Call('_BayesANT_log_MultKmers_cpp', PACKAGE = 'BayesANT', x, x_tilde)
}

compute_probs_MultKmers <- function(K, priors, new_kmers) {
    .Call('_BayesANT_compute_probs_MultKmers', PACKAGE = 'BayesANT', K, priors, new_kmers)
}

